/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutAnimate: typeof import('@nutui/nutui-taro')['Animate']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
